# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GOLANGCILINT: "go tool -modfile={{.ROOT_DIR}}/tools/golangci-lint.mod golangci-lint"
  GOOSE: "go tool -modfile={{.ROOT_DIR}}/tools/goose.mod goose"
  DEV_COMPOSE: "-f deploy/docker-compose-dev.yml"

tasks:
  fmt:
    desc: Форматирование кода
    cmd: "{{.GOLANGCILINT}} fmt ./..."
    silent: true

  lint:
    desc: Линтинг кода
    cmd: "{{.GOLANGCILINT}} run --fix ./..."
    silent: true

  test:unit:
    desc: Запуск тестов
    cmd: go test ./...
    silent: true

  check:
    desc: Набор проверок перед коммитом
    deps: [fmt, lint, test:unit]
    silent: true

  ci:
    desc: Набор проверок без исправлений
    cmds:
      - "{{.GOLANGCILINT}} fmt --diff ./..."
      - "{{.GOLANGCILINT}} run ./..."
      - task test:unit
    silent: true

  dev:start:
    desc: Развернуть инфраструктуру для разработки
    dotenv: [.env]
    cmd: docker compose {{.DEV_COMPOSE}} up -d
    silent: true

  dev:stop:
    desc: Развернуть инфраструктуру для разработки
    dotenv: [.env]
    cmd: docker compose {{.DEV_COMPOSE}} down -v
    silent: true
