// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type IdempotencyKey struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
	CreatedAt   time.Time
}

type Subscription struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Tariff struct {
	ID                uuid.UUID
	Name              string
	MonthlyPriceMinor int64
	MessageLimit      int32
	Type              string
	IsBaseTariff      bool
	CreatedAt         time.Time
}
