// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const findActiveSubscriptionByOrganization = `-- name: FindActiveSubscriptionByOrganization :one
SELECT
    id,
    user_id,
    organization_id,
    tariff_id,
    status,
    message_allowance,
    current_period_start,
    current_period_end,
    payment_id
FROM subscriptions
WHERE organization_id = $1 AND status = 'active'
`

type FindActiveSubscriptionByOrganizationRow struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
}

func (q *Queries) FindActiveSubscriptionByOrganization(ctx context.Context, organizationID *uuid.UUID) (FindActiveSubscriptionByOrganizationRow, error) {
	row := q.db.QueryRow(ctx, findActiveSubscriptionByOrganization, organizationID)
	var i FindActiveSubscriptionByOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.TariffID,
		&i.Status,
		&i.MessageAllowance,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
	)
	return i, err
}

const findActiveSubscriptionByUser = `-- name: FindActiveSubscriptionByUser :one
SELECT
    id,
    user_id,
    organization_id,
    tariff_id,
    status,
    message_allowance,
    current_period_start,
    current_period_end,
    payment_id
FROM subscriptions
WHERE user_id = $1 AND status = 'active'
`

type FindActiveSubscriptionByUserRow struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
}

func (q *Queries) FindActiveSubscriptionByUser(ctx context.Context, userID *uuid.UUID) (FindActiveSubscriptionByUserRow, error) {
	row := q.db.QueryRow(ctx, findActiveSubscriptionByUser, userID)
	var i FindActiveSubscriptionByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.TariffID,
		&i.Status,
		&i.MessageAllowance,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
	)
	return i, err
}

const findBaseTariff = `-- name: FindBaseTariff :one
SELECT id, name, monthly_price_minor, message_limit, type, is_base_tariff
FROM tariffs
WHERE is_base_tariff
`

type FindBaseTariffRow struct {
	ID                uuid.UUID
	Name              string
	MonthlyPriceMinor int64
	MessageLimit      int32
	Type              string
	IsBaseTariff      bool
}

func (q *Queries) FindBaseTariff(ctx context.Context) (FindBaseTariffRow, error) {
	row := q.db.QueryRow(ctx, findBaseTariff)
	var i FindBaseTariffRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPriceMinor,
		&i.MessageLimit,
		&i.Type,
		&i.IsBaseTariff,
	)
	return i, err
}

const findIdempotency = `-- name: FindIdempotency :one
SELECT key, operation, request_hash, resource_id
FROM idempotency_keys
WHERE key = $1
`

type FindIdempotencyRow struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) FindIdempotency(ctx context.Context, key string) (FindIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findIdempotency, key)
	var i FindIdempotencyRow
	err := row.Scan(
		&i.Key,
		&i.Operation,
		&i.RequestHash,
		&i.ResourceID,
	)
	return i, err
}

const findIdempotencyForUpdate = `-- name: FindIdempotencyForUpdate :one
SELECT key, operation, request_hash, resource_id
FROM idempotency_keys
WHERE key = $1
FOR UPDATE
`

type FindIdempotencyForUpdateRow struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) FindIdempotencyForUpdate(ctx context.Context, key string) (FindIdempotencyForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findIdempotencyForUpdate, key)
	var i FindIdempotencyForUpdateRow
	err := row.Scan(
		&i.Key,
		&i.Operation,
		&i.RequestHash,
		&i.ResourceID,
	)
	return i, err
}

const findSubscription = `-- name: FindSubscription :one
SELECT
    id,
    user_id,
    organization_id,
    tariff_id,
    status,
    message_allowance,
    current_period_start,
    current_period_end,
    payment_id
FROM subscriptions
WHERE id = $1
`

type FindSubscriptionRow struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
}

func (q *Queries) FindSubscription(ctx context.Context, id uuid.UUID) (FindSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, findSubscription, id)
	var i FindSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.TariffID,
		&i.Status,
		&i.MessageAllowance,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
	)
	return i, err
}

const findTariff = `-- name: FindTariff :one
SELECT id, name, monthly_price_minor, message_limit, type, is_base_tariff
FROM tariffs
WHERE id = $1
`

type FindTariffRow struct {
	ID                uuid.UUID
	Name              string
	MonthlyPriceMinor int64
	MessageLimit      int32
	Type              string
	IsBaseTariff      bool
}

func (q *Queries) FindTariff(ctx context.Context, id uuid.UUID) (FindTariffRow, error) {
	row := q.db.QueryRow(ctx, findTariff, id)
	var i FindTariffRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MonthlyPriceMinor,
		&i.MessageLimit,
		&i.Type,
		&i.IsBaseTariff,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys (key, operation, request_hash, resource_id)
VALUES ($1, $2, $3, $4)
`

type InsertIdempotencyParams struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.Key,
		arg.Operation,
		arg.RequestHash,
		arg.ResourceID,
	)
	return err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (
    id,
    user_id,
    organization_id,
    tariff_id,
    status,
    message_allowance,
    current_period_start,
    current_period_end
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertSubscriptionParams struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.TariffID,
		arg.Status,
		arg.MessageAllowance,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}

const insertTariff = `-- name: InsertTariff :exec
INSERT INTO tariffs (id, name, monthly_price_minor, message_limit, type, is_base_tariff)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTariffParams struct {
	ID                uuid.UUID
	Name              string
	MonthlyPriceMinor int64
	MessageLimit      int32
	Type              string
	IsBaseTariff      bool
}

func (q *Queries) InsertTariff(ctx context.Context, arg InsertTariffParams) error {
	_, err := q.db.Exec(ctx, insertTariff,
		arg.ID,
		arg.Name,
		arg.MonthlyPriceMinor,
		arg.MessageLimit,
		arg.Type,
		arg.IsBaseTariff,
	)
	return err
}

const listTariffs = `-- name: ListTariffs :many
SELECT id, name, monthly_price_minor, message_limit, type, is_base_tariff
FROM tariffs
ORDER BY created_at, id
`

type ListTariffsRow struct {
	ID                uuid.UUID
	Name              string
	MonthlyPriceMinor int64
	MessageLimit      int32
	Type              string
	IsBaseTariff      bool
}

func (q *Queries) ListTariffs(ctx context.Context) ([]ListTariffsRow, error) {
	rows, err := q.db.Query(ctx, listTariffs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTariffsRow
	for rows.Next() {
		var i ListTariffsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MonthlyPriceMinor,
			&i.MessageLimit,
			&i.Type,
			&i.IsBaseTariff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueSubscriptions = `-- name: LockDueSubscriptions :many
SELECT
    subscriptions.id,
    subscriptions.user_id,
    subscriptions.organization_id,
    subscriptions.tariff_id,
    subscriptions.status,
    subscriptions.message_allowance,
    subscriptions.current_period_start,
    subscriptions.current_period_end,
    subscriptions.payment_id,
    tariffs.name,
    tariffs.monthly_price_minor,
    tariffs.message_limit,
    tariffs.type,
    tariffs.is_base_tariff
FROM subscriptions
JOIN tariffs ON tariffs.id = subscriptions.tariff_id
WHERE subscriptions.status = 'active'
  AND subscriptions.current_period_end <= $1
ORDER BY subscriptions.id
FOR UPDATE OF subscriptions SKIP LOCKED
`

type LockDueSubscriptionsRow struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
	Name               string
	MonthlyPriceMinor  int64
	MessageLimit       int32
	Type               string
	IsBaseTariff       bool
}

func (q *Queries) LockDueSubscriptions(ctx context.Context, currentPeriodEnd time.Time) ([]LockDueSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, lockDueSubscriptions, currentPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockDueSubscriptionsRow
	for rows.Next() {
		var i LockDueSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.TariffID,
			&i.Status,
			&i.MessageAllowance,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.PaymentID,
			&i.Name,
			&i.MonthlyPriceMinor,
			&i.MessageLimit,
			&i.Type,
			&i.IsBaseTariff,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubscription = `-- name: LockSubscription :one
SELECT
    id,
    user_id,
    organization_id,
    tariff_id,
    status,
    message_allowance,
    current_period_start,
    current_period_end,
    payment_id
FROM subscriptions
WHERE id = $1
FOR UPDATE
`

type LockSubscriptionRow struct {
	ID                 uuid.UUID
	UserID             *uuid.UUID
	OrganizationID     *uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
}

func (q *Queries) LockSubscription(ctx context.Context, id uuid.UUID) (LockSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, lockSubscription, id)
	var i LockSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.TariffID,
		&i.Status,
		&i.MessageAllowance,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.PaymentID,
	)
	return i, err
}

const renewSubscription = `-- name: RenewSubscription :exec
UPDATE subscriptions
SET
    message_allowance = $2,
    current_period_start = $3,
    current_period_end = $4,
    payment_id = $5,
    updated_at = now()
WHERE id = $1
`

type RenewSubscriptionParams struct {
	ID                 uuid.UUID
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
	PaymentID          pgtype.Text
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) error {
	_, err := q.db.Exec(ctx, renewSubscription,
		arg.ID,
		arg.MessageAllowance,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.PaymentID,
	)
	return err
}

const updateSubscription = `-- name: UpdateSubscription :exec
UPDATE subscriptions
SET
    tariff_id = $2,
    status = $3,
    message_allowance = $4,
    current_period_start = $5,
    current_period_end = $6,
    updated_at = now()
WHERE id = $1
`

type UpdateSubscriptionParams struct {
	ID                 uuid.UUID
	TariffID           uuid.UUID
	Status             string
	MessageAllowance   int64
	CurrentPeriodStart time.Time
	CurrentPeriodEnd   time.Time
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateSubscription,
		arg.ID,
		arg.TariffID,
		arg.Status,
		arg.MessageAllowance,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	return err
}
