// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type IdempotencyKey struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
	CreatedAt   pgtype.Timestamptz
}

type Organization struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	OrganizationID *uuid.UUID
	Role           string
	CreatedAt      pgtype.Timestamptz
}
