// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package postgres

import (
	"context"

	"uuid"
)

const findIdempotency = `-- name: FindIdempotency :one
SELECT key, operation, request_hash, resource_id
FROM idempotency_keys
WHERE key = $1
`

type FindIdempotencyRow struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) FindIdempotency(ctx context.Context, key string) (FindIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, findIdempotency, key)
	var i FindIdempotencyRow
	err := row.Scan(
		&i.Key,
		&i.Operation,
		&i.RequestHash,
		&i.ResourceID,
	)
	return i, err
}

const findIdempotencyForUpdate = `-- name: FindIdempotencyForUpdate :one
SELECT key, operation, request_hash, resource_id
FROM idempotency_keys
WHERE key = $1
FOR UPDATE
`

type FindIdempotencyForUpdateRow struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) FindIdempotencyForUpdate(ctx context.Context, key string) (FindIdempotencyForUpdateRow, error) {
	row := q.db.QueryRow(ctx, findIdempotencyForUpdate, key)
	var i FindIdempotencyForUpdateRow
	err := row.Scan(
		&i.Key,
		&i.Operation,
		&i.RequestHash,
		&i.ResourceID,
	)
	return i, err
}

const findOrganization = `-- name: FindOrganization :one
SELECT id, name
FROM organizations
WHERE id = $1
`

type FindOrganizationRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) FindOrganization(ctx context.Context, id uuid.UUID) (FindOrganizationRow, error) {
	row := q.db.QueryRow(ctx, findOrganization, id)
	var i FindOrganizationRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, password_hash, organization_id, role
FROM users
WHERE email = $1
`

type FindUserByEmailRow struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	OrganizationID *uuid.UUID
	Role           string
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OrganizationID,
		&i.Role,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, password_hash, organization_id, role
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	OrganizationID *uuid.UUID
	Role           string
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.OrganizationID,
		&i.Role,
	)
	return i, err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO idempotency_keys (key, operation, request_hash, resource_id)
VALUES ($1, $2, $3, $4)
`

type InsertIdempotencyParams struct {
	Key         string
	Operation   string
	RequestHash []byte
	ResourceID  uuid.UUID
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.Key,
		arg.Operation,
		arg.RequestHash,
		arg.ResourceID,
	)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (id, name)
VALUES ($1, $2)
`

type InsertOrganizationParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.Exec(ctx, insertOrganization, arg.ID, arg.Name)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, email, password_hash, organization_id, role)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   string
	OrganizationID *uuid.UUID
	Role           string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.OrganizationID,
		arg.Role,
	)
	return err
}
