{
 "title": "Business",
 "tags": [ "subscriptions" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (messages_consumed_total)"
    }
   ]
  },
  {
   "title": "Tokens used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (tokens_used_total)"
    }
   ]
  },
  {
   "title": "Overdraft",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (type) (overdraft_count)"
    }
   ]
  },
  {
   "title": "Payments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (status) (payments_total)"
    }
   ]
  }
 ]
}